### ISSUE TITLE
Incorrent time to close ballot

### ISSUE THREAD

**Issue by shkron** [oraclesorg/oracles-dapps-voting#100]
<img width="281" alt="screen shot 2018-02-22 at 9 36 42 pm" src="https://user-images.githubusercontent.com/9002435/36579589-b5fcce8c-1818-11e8-8e63-5cdc92a2ad2d.png">

On Sokol:
KEYS BALLOT ID: 1
KEYS BALLOT ID: 2

Both ballots are still active.

**Comment by shkron** [comment]
<img width="219" alt="screen shot 2018-02-22 at 9 43 11 pm" src="https://user-images.githubusercontent.com/9002435/36579715-6ea23d0a-1819-11e8-89d4-22d7db6cbc4f.png">

After refresh the ballots show 00:00 time to close. But the issue is reproducible and during the reproduction ballot become active.

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-voting/pull/109.
