### ISSUE TITLE
(Feature) Voting dapp doesn't load with TrustWallet browser

### ISSUE THREAD

**Issue by maratP** [oraclesorg/oracles-dapps-voting#122]
Tested using voting dapp with TrustWallet

1. Import voting key-  pass (able to see transactions and  balance) 
2. Select POA network - pass
3. Load voting dapp in TdustWallet browser - fail 

Error:

You haven't chosen any account in MetaMask. Please, choose your voting key in MetaMask and reload the page. Check POA Network wiki

ANDROID app on Galaxy S9+

**Comment by vikmeup** [comment]
Thank you for reporting! I will test it in Trust Wallet to see how we can fix it!

**Comment by 6proof** [comment]
Thanks Viktor!  Anything we can do to help test?

**Comment by 6proof** [comment]
Is there an update on this; any progress?  If there is an identified possible cause please post so we community members can help resolve.  Thanks very much!

**Comment by varasev** [comment]
@maratP Please clarify for your case, do you see the error after the page is reloaded?

**Comment by igorbarinov** [comment]
@varasev I see the error after the page is reloaded

**Comment by varasev** [comment]
I'm testing that on Android 7 and see the same error, but only when I load the page for the first time or when I use URL address field in Trust Wallet browser.

The error doesn't appear when I try to reload the page by tapping on `Reload` menu item.

@igorbarinov Could you repeat the same steps with `Reload` feature of the browser?

**Comment by varasev** [comment]
After some tests, it was getting clear that the cause of the error is in `window.web3` object - sometimes (randomly) it is `undefined` in Android Trust Wallet browser: https://github.com/poanetwork/poa-dapps-voting/blob/7c8065e99664eb2f2b5447b74537e723a405532a/src/getWeb3.js#L8-L11

Tested in Android 7.1.

@vikmeup could you take a look at this?

**Comment by madcake** [comment]
The problem in ServiceWorker. It caches all the data and there is no way to do the injection. Try removing index.html.

**Comment by varasev** [comment]
@madcake Inside the built `service-worker.js` I see `index.html` in the array of files to be cached:

![image](https://user-images.githubusercontent.com/33550681/41790646-dfd6667c-765b-11e8-9146-1743f3998b63.png)

Did you mean to remove `index.html` from that array?

I'll try to add `index.html` to `staticFileGlobsIgnorePatterns` array in our `webpack.config.prod.js`.

**Comment by madcake** [comment]
Yes, try remove it, and clean cache.
<img width="1552" alt="2018-06-23 0 54 41" src="https://user-images.githubusercontent.com/133312/41791481-0df364c8-7680-11e8-9188-a66318eca37f.png">

**Comment by varasev** [comment]
@madcake ok, thanks for the tip!

**Comment by 6proof** [comment]
Looks like progress is being made - anything we can do to help test?

**Comment by varasev** [comment]
@6proof thanks, the help is not needed yet.

**Comment by varasev** [comment]
Somebody who has Android 7/8, please test Voting DApp on the page https://varasev.github.io with Trust Wallet browser.

The browser cache needs to be cleaned before: `Settings -> Clear Browser Cache.`

If the error still appears or you see `error 2` (it's my short debug error message), open https://varasev.github.io/service-worker.js and reload this URL to ensure DApp uses updated code. Then try again to browse https://varasev.github.io.

I don't see the error anymore on my Android 7.1.

**Comment by igorbarinov** [comment]
Looks good on Android 8.1.0 and Trust Wallet 1.5.126. 
I didn't clear cache browser, all happened by itself.

![image](https://user-images.githubusercontent.com/424628/41838184-fd972876-785f-11e8-920c-52ff180977ce.png)

@6proof how it works for u?

**Comment by phahulin** [comment]
Works for me too on Android 7.1.1 after clearing cache

**Comment by varasev** [comment]
@maratP could you recheck https://voting.poa.network with your Android device? Please, clear browser cache before checking (`Settings -> Clear Browser Cache`).

**Comment by maratP** [comment]
Tested dapps browser of TrustWallet https://voting.poa.network

I am now able to load this page and didn't have to clear cache

Tested on Android 8.0.0

**Comment by maratP** [comment]
Both links worked for me

https://varasev.github.io
https://voting.poa.network

I believe we can close it now 👍🏻

**Comment by varasev** [comment]
Ok. This issue was fixed in https://github.com/poanetwork/poa-dapps-voting/pull/142.
