### ISSUE TITLE
(Fix) check status of voting and finalization transactions

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-voting#123]
**Problem**: statuses of voting and finalization transactions are not checked
**Solution**: status should be checked. Success alert should appear only if a status is true. Error alert, otherwise

**Comment by rstormsf** [comment]
I assume @vbaranov means to check `status !==` `0x0` or `0x1`

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-voting/pull/145.
