### ISSUE TITLE
Change logic for sending transactions

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#125]
now we are using `on('transactionHash')` and `on('receipt')`  event listeners. This breaks when it's working with Trust wallet. 

So instead we should use plain and simple `web3.eth.sendTransaction` by generating data from `encodeABI()` and passing to web3.eth.sendTransaction

**Comment by varasev** [comment]
@rstormsf did you mean Android or iOS version of Trust Wallet?

**Comment by varasev** [comment]
Fixed in #158.
