### ISSUE TITLE
(Showstopper) Sokol network keeps loading 

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#132]
For some reason, it doesn't always load the Sokol Voting Dapp.
Need investigation and finding the root cause and possible bug fixed.

Hypothesis is that there are probably incorrect implementation of handling event loading. There are quite a few already and the  App cannot process them all on time.

I can't load the  app at all on Sokol

**Comment by rstormsf** [comment]
Seems  like the  issue was with public RPC url....works fine now

**Comment by phahulin** [comment]
Though I can't reproduce it now and don't observe increased cpu/memory usage in the past 24 hours, I noticed in metamask logs that voting dapp on sokol makes about 900 requests while loading. Probably when there is additional load on the network, their combined effect impacts performance. It's also possible that cloudflare limits requests to that endpoint.

As I undetstand by default all ballots are displayed, maybe display only active ones?

**Comment by vbaranov** [comment]
>As I undetstand by default all ballots are displayed, maybe display only active ones?

It will mitigate. I believe, mostly active ballots are interesting for validators. I support this suggestion. Also, we could implement retrieving of ballot's properties in one call: https://github.com/poanetwork/poa-network-consensus-contracts/issues/128

**Comment by varasev** [comment]
> Also, we could implement retrieving of ballot's properties in one call: https://github.com/poanetwork/poa-network-consensus-contracts/issues/128

It is not always possible to return all of the data in a single function because Solidity has a stack depth limit but it's possible to make two or three functions that would return a data piece by piece.

**Comment by varasev** [comment]
Also, I described my thoughts about excess requests in https://github.com/poanetwork/poa-dapps-voting/issues/124#issuecomment-385615189 a month ago.
