### ISSUE TITLE
(Bug) Should be working in TrustWallet

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#141]
https://voting.poa.network
Open in Trust wallet - doesn't work.

**Comment by varasev** [comment]
@rstormsf Do you mean the same error as described in https://github.com/poanetwork/poa-dapps-voting/issues/122?

**Comment by igorbarinov** [comment]
It doesn't work in the Android version of Trust wallet. I'm not sure if it's related to dapp implementation. 
Works in iOS version.

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-voting/pull/142.
