### ISSUE TITLE
(Bug) negative value of minutes in alert

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-voting#153]
![screen shot 2018-07-12 at 13 00 08](https://user-images.githubusercontent.com/4341812/42626788-dc7e2ae6-85d3-11e8-9275-94da22733923.png)
![screen shot 2018-07-12 at 13 00 22](https://user-images.githubusercontent.com/4341812/42626790-dd1dc394-85d3-11e8-8ee1-50823b243fe1.png)

**Comment by varasev** [comment]
Fixed in #158.
