### ISSUE TITLE
(UI Bug) wrong "The key null..." alert on ballot creation if Metamask is locked

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-voting#156]
![screencapture-localhost-3002-poa-dapps-voting-new-2018-07-12-13_43_23 1](https://user-images.githubusercontent.com/4341812/42628852-0b7cba3c-85da-11e8-97e9-0d7224d9693b.png)

The suggestion is, if Metamask is locked, show corresponding alert everywhere including at ballot's creation button:
![screencapture-localhost-3002-poa-dapps-voting-new-2018-07-12-13_47_40](https://user-images.githubusercontent.com/4341812/42628898-2d7224c4-85da-11e8-9269-3f89e45dc5a3.png)

**Comment by varasev** [comment]
Done in #177.
