### ISSUE TITLE
(UI) Restyling

### ISSUE THREAD

**Issue by gabitoesmiapodo** [oraclesorg/oracles-dapps-voting#164]
Continuing https://github.com/poanetwork/poa-dapps-voting/pull/160

Apply these changes to the UI https://github.com/poanetwork/poa-dapps-voting/pull/160#issuecomment-407815568

**Comment by pashagonchar** [comment]
Sokol
![poa_governance_app_new_ballot_2_sokol](https://user-images.githubusercontent.com/16716926/43633720-bfa15ec0-9712-11e8-9c9f-ac5a523feb3c.png)
![poa_governance_app_new_ballot_3_sokol](https://user-images.githubusercontent.com/16716926/43633722-bfbde284-9712-11e8-997d-df9e452851e7.png)
![poa_governance_app_new_ballot_sokol](https://user-images.githubusercontent.com/16716926/43633723-bfddb348-9712-11e8-8922-0e51eecb3ab7.png)
![poa_governance_app_sokol](https://user-images.githubusercontent.com/16716926/43633724-bfffce10-9712-11e8-9a53-527247032d3c.png)

**Comment by pashagonchar** [comment]
Zeplin:
https://zpl.io/aRYLQZK
https://zpl.io/V0yWYrE
https://zpl.io/agvDMmO
https://zpl.io/anKNWBv

**Comment by varasev** [comment]
Please add the label `(to close)` for `00:00` value as well.

**Comment by gabitoesmiapodo** [comment]
@pashagonchar Got it.
@varasev Noticed.

**Comment by varasev** [comment]
Hi @pashagonchar We'll also have another type of the ballot - it supposes to take three variants of votes: send, burn and freeze. So, the ballot card will be different. I tried to make some draft to show how it should look. Could you add this type of the ballot card to the layout?

![image](https://user-images.githubusercontent.com/33550681/43942672-9983d352-9c81-11e8-8763-d98494fd2d16.png)

**Comment by pashagonchar** [comment]
Hi @varasev , ok I'll make this type of ballot

**Comment by pashagonchar** [comment]
![poa_governance_app_sokol_2](https://user-images.githubusercontent.com/16716926/43989192-ba718af6-9d4d-11e8-924a-6f7661733f78.png)
@varasev https://zpl.io/VxlmwQ3

**Comment by varasev** [comment]
@pashagonchar Ok, thanks!

**Comment by varasev** [comment]
@pashagonchar another question: `Load More Ballot` button seems not to be visible enough. Could we make it with some border or background? Or expand the top and the bottom whitespace around it? What do you think?

**Comment by pashagonchar** [comment]
![poa_governance_app_sokol_2](https://user-images.githubusercontent.com/16716926/44035892-348375bc-9f19-11e8-8861-f0a10aac8c61.png)
@varasev

**Comment by varasev** [comment]
@pashagonchar thanks!

**Comment by varasev** [comment]
@gabitoesmiapodo could you add the border for `Load More Ballots` button as it's shown above?

**Comment by gabitoesmiapodo** [comment]
@varasev yeah, see https://github.com/poanetwork/poa-dapps-voting/pull/166#issuecomment-412601990

**Comment by varasev** [comment]
Merged in https://github.com/poanetwork/poa-dapps-voting/pull/166.
