### ISSUE TITLE
(Update) New style for xDai Network

### ISSUE THREAD

**Issue by varasev** [oraclesorg/oracles-dapps-voting#187]
We need to have separate colors and logo for xDai network in Voting DApp. Example (yellow-orange color scheme): https://blockscout.com/poa/dai

**Comment by varasev** [comment]
![xdai_governance_app_new_ballot_3](https://user-images.githubusercontent.com/16716926/49885390-c79ab600-fe3f-11e8-93ae-c6f7afc928aa.png)
![xdai_governance_app_new_ballot](https://user-images.githubusercontent.com/16716926/49885391-c8334c80-fe3f-11e8-8c3b-3d8e1f57b11c.png)
![xdai_governance_app](https://user-images.githubusercontent.com/16716926/49885392-c8334c80-fe3f-11e8-8bc1-98c177eb940e.png)

Zeplin

https://zpl.io/V0R9rpl

https://zpl.io/2EPm4Ry

https://zpl.io/adrxKYe

**Comment by gabitoesmiapodo** [comment]
@varasev 

I'll start working on this issue.

**Comment by gabitoesmiapodo** [comment]
@varasev 

Could you update my permissions so I can commit, push, etc.?

I'm currently trying to push a new branch for this issue, but I'm unable to do so.

**Comment by vbaranov** [comment]
@gabitoesmiapodo please check your access

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

I seem to be able to push to https://github.com/poanetwork/poa-dapps-keys-generation , https://github.com/poanetwork/token-wizard , etc., but not here.

Not sure why, everything seems OK on my side as far as I can tell.

**Comment by vbaranov** [comment]
I mean permissions were granted. Doesn’t it work for you?

**Comment by gabitoesmiapodo** [comment]
@vbaranov Nope... that's weird. Tried with a new branch, and I get the same error.

```
Pushing to git@github.com:poanetwork/poa-dapps-voting.git
ERROR: Permission to poanetwork/poa-dapps-voting.git denied to gabitoesmiapodo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Completed with errors, see above
```

The repo obviously exists, so I assumed it had something to do with permissions.

Tried the same with the repositories I mentioned before, and everything works.

**Comment by vbaranov** [comment]
@gabitoesmiapodo please try again. Should work.

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Yeah, it does now, thank you!
