### ISSUE TITLE
(Fix) give the ability to choose a time for ballot's end time

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-voting#35]
**Problem**: User can only choose a date for ballot's end time field.
**Solution**: Give the ability to choose a time for ballot's end time too

**Comment by igorbarinov** [comment]
@vbaranov I didn't get it
a user can choose data for the end time
in solution should be start time also?

**Comment by vbaranov** [comment]
@igorbarinov I mean a validator can choose only a date, not time https://monosnap.com/file/STgSpI8Wz7EGi9KyhNZIStofY0aheT. Thus, they can't create short ballots.

>in solution should be start time also?

Ballot starts immediately after creation. If you think, we should give an ability to validator to manage its start, I'll add it.
