### ISSUE TITLE
(Design UI) Need different style for inactive ballots

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#54]
Right now we have the following picture:
![image](https://user-images.githubusercontent.com/9360827/34628074-ec038cb8-f217-11e7-891c-72618e9df999.png)

Old ballots first, new ballots to the bottom

@igorbarinov need your call on that...
I believe we should style old ballots differently and display new ones on the top

**Comment by igorbarinov** [comment]
- We should add filtering to hide/differentiate old ballots
- I agree with display new ballots on top

@vbaranov do we have a working mock interface with testrpc/without a chain? we discussed it few months ago with the previous version of voting app
