### ISSUE TITLE
(UI) run `areBallotParamsValid` smart contract function before creating ballot

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#61]

**Comment by vbaranov** [comment]
@rstormsf It looks like a double check. We already do it inside `createVotingForKeys` method:
https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/contracts/VotingToChangeKeys.sol#L69 .

**Comment by rstormsf** [comment]
Nope, u do it on smart contract level, but we should not let to click on create ballot if ballot params are invalid
