### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#7]
1. Don't navigate to the next screen as if I were proposing a new" miner creation if I selected a ballot to REMOVE key
Please also have some explanations for each field, what they mean and how to use it. (mining key, affected key, etc.)

2. When I created a ballot, I should be automatically voted (doesn't work now) 

3. For some reason I had 20 rows of proposals when I created a ballot

4. I was able to vote NO for proposal.

5. I was able to vote YES for proposal

6. UI - please change Button's fields from VOTE TO Yes/No (or better names) 
7. Please change YES to the right and No to the left. ( I believe that's how it's being used in most UI popups)

8. Let the creator choose EXPIRATION DATE for ballot
<img width="1173" alt="screen shot 2017-10-01 at 11 13 03 am" src="https://user-images.githubusercontent.com/9360827/31057555-88ad8d7c-a699-11e7-9426-450cf8b05ab7.png">

**Comment by rstormsf** [comment]
License ID field  - doesn't let you enter some characters.

**Comment by rstormsf** [comment]
Can't create a ballot:
<img width="546" alt="screen shot 2017-10-04 at 12 24 02 am" src="https://user-images.githubusercontent.com/9360827/31164078-606ab04e-a89a-11e7-9f88-86efdb19ea2b.png">

**Comment by rstormsf** [comment]
<img width="1164" alt="screen shot 2017-10-04 at 12 25 50 am" src="https://user-images.githubusercontent.com/9360827/31164134-9a8e9bbe-a89a-11e7-9e24-cf4e0499fc5b.png">

after ballot is created there are at least 3 rows of the same thing

**Comment by igorbarinov** [comment]
the issue is outdated and should be closed
