### ISSUE TITLE
Ballots UI -- Need BALLOT MEMO or DESCRIPTION other observations/suggestions

### ISSUE THREAD

**Issue by johnnynuuma** [oraclesorg/oracles-dapps-voting#77]
Need MEMO or BALLOT DESCRIPTION so know what we are voting on.

-NAME suggest PROPOSER
-PROXY BALLOT ID suggest  BALLOT ID
-Unnecessary text ("Finalization is available after ballot time is finished ") when Ballot is already Finalized
-TIME suggest BALLOT TIME
-Add STATUS column
-Does search work?  and/or add filtering
-Sort order by BALLOT ID descending, i.e. most recent ballots first.

In general, inefficient use of space ... perhaps move towards summary -> detail ( drill down ) model.
I will try to provide mock up to describe what I mean.
![sokol - poa network governance dapp - google chrome_001](https://user-images.githubusercontent.com/22530182/35072987-c42c0822-fb9b-11e7-9912-cc83038c6dcc.png)

**Comment by rstormsf** [comment]
@johnnynuuma thank you so much ! we will fix all of those issues mentioned

**Comment by vbaranov** [comment]
@johnnynuuma 

> Need MEMO or BALLOT DESCRIPTION so know what we are voting on.

Memo was added

>-NAME suggest PROPOSER

Done

>-PROXY BALLOT ID suggest BALLOT ID

Every Ballot type has different IDs types now:
 - "KEYS BALLOT ID"
 - "PROXY BALLOT ID"
 - "CONSENSUS BALLOT ID" 

>-Unnecessary text ("Finalization is available after ballot time is finished ") when Ballot is already Finalized

Hint text was removed for finalized ballots

> -TIME suggest BALLOT TIME

Done

>-Add STATUS column

`TO FINALIZE` filter was introduced. Also, active and not active cards have different color scheme now.

>-Does search work? and/or add filtering

Added search by memo, mining key. It should work for all other properties of ballots.

>-Sort order by BALLOT ID descending, i.e. most recent ballots first.

Done. New ballots are at the top.

Thank you for your suggestions!
