### ISSUE TITLE
how to finish ballot? 

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#8]
@vbaranov

**Comment by vbaranov** [comment]
For now, any activity (creating of new ballot and voting) of any valid notary will check for finalizing of previous ballots and finalize them. We’ll add “Finalize” button for every ballot in the next release.

**Comment by rstormsf** [comment]
@vbaranov I created new ballot and it didn't finish my previous ballots.
Instead of using English, please point me to the code where it's being used.

**Comment by vbaranov** [comment]
Your question from the title wasn't about to point to the code, right?
The finalization of ballots described [here](https://github.com/oraclesorg/oracles-contract/blob/master/src/BallotsManager.sol). `checkBallotsActivity ` method.

**Comment by vbaranov** [comment]
@rstormsf and I see that it finished it. What did you expect?
