### ISSUE TITLE
UX - Error Trapping - Max Time

### ISSUE THREAD

**Issue by jflowers1974** [oraclesorg/oracles-dapps-voting#81]
Perhaps limit the max time that a ballot contract may be open to X (whatever X is deemed ok).  This would limit the potential for ballots that never resolve or resolve over long periods of time.

I would suggest 14 calendar days as the upper boundary for this.

**Comment by micwebnet** [comment]
2w seems like a sound default ballot expiration term.

-MM

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-voting/pull/109.
