### ISSUE TITLE
UI - Ballot Contract Design

### ISSUE THREAD

**Issue by jflowers1974** [oraclesorg/oracles-dapps-voting#82]
I was thinking - in order to help drill through the intended logic - 

Add Key, Remove Key, Sway Key radio buttons are removed and replaced with a drop down.  This would save space. 

Then below this, remove the 'col' with the: mining key, payout key, voting key -  and instead have another drop down.  

![poa19012018_2](https://user-images.githubusercontent.com/4926929/35180165-c3035896-fd5e-11e7-9d64-b684dcf598c9.jpg)

This would have the effect of forcing a logical progression:  Management Function -> Key Type

**Comment by rstormsf** [comment]
I like the autopopulation with + 2 days. Good idea!

**Comment by johnnynuuma** [comment]
Here are my thoughts on the "Ballot End Time"  field

I hope it is self-evident in picture
![sokol - poa network governance dapp - google chrome_005](https://user-images.githubusercontent.com/22530182/35186866-3555b274-fdd0-11e7-83e8-159ca1e4eb7a.png)

**Comment by johnnynuuma** [comment]
Regarding "Ballot End Time" thinking it should be calculated ... user specifies "Ballot Duration" like this:

![sokol - poa network governance dapp - google chrome_005](https://user-images.githubusercontent.com/22530182/35188977-1607e2f4-fdf6-11e7-89ff-c8bdcd20b6c7.png)

**Comment by rstormsf** [comment]
it's done
